### ISSUE TITLE
Website links are not working

### ISSUE THREAD

**Issue by GinoGiotto** [metamath/metamath-website-scripts#17]
Not sure what is the appropriate repository to report this, but a lot of links of the metamath website aren't working, here are some of them:

https://us.metamath.org/mpeuni/mmset.html
https://us.metamath.org/ileuni/mmil.html
https://us.metamath.org/mpeuni/mmtheorems.html
https://us.metamath.org/mpeuni/conventions.html
https://us.metamath.org/mpeuni/ax-mp.html

It always gives `404 Not Found` error.

**Comment by digama0** [comment]
See https://groups.google.com/g/metamath/c/P0D4h2uIj2k for status; the site is undergoing "scheduled maintenance".

(In general, the google group is the best place to go to report service interruptions, as opposed to issues in the site due to bad data or scripts.)

**Comment by tirix** [comment]
So this is a special case, right? There will not be a 3-hours downtime every time the site is being updated e.g. with a new version of `set.mm`?

**Comment by digama0** [comment]
Yes, I just made a mistake when running the update script. Specifically, `./regenerate-website.sh` is written in such a way that if there is an error in an earlier stage, such as failing to download the seed repo because of a misspelled branch name, it will continue to the other stages, deleting the `www` directory, creating the site contents (which fails because most files are not available), and then copies the site to the production copy (even though it's basically empty). This also happens if you Ctrl-C abort `build-website.sh`.

This seems like a pretty nasty issue, it might be safer to abort the copy if an earlier stage failed, but on the other hand if something breaks it is good to get notification that something is wrong rather than just silently failing and resulting in an out of date website that may take longer to notice.

**Comment by GinoGiotto** [comment]
Seems the website is working now, so I'm closing this issue. As requested I will check out https://groups.google.com/g/metamath/c/P0D4h2uIj2k if I'll find any related problem.
